
version: '3.4'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'CSE312-Project'
      MYSQL_USER: 'Felipe'
      MYSQL_PASSWORD: 'Gallardo'
      MYSQL_ROOT_PASSWORD: 'Gallardo'
    ports:
      - "3306:3306"
  app:
    build: .
    environment:
      DATABASE_USER: 'Felipe'
      DATABASE_PASSWORD: 'Gallardo'
      WAIT_HOSTS: mysql:3306
    ports:
      - "8080:8000"